services:
  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    environment:
      - SUMMARIZATION_SERVICE_URL=http://summarization_service:5001/summarize
    depends_on:
      - summarization_service

  summarization_service:
    build: ./summarization_service
    ports:
      - "5001:5001"
    env_file:
      - ./summarization_service/.env
    depends_on:
      - video_service

  video_service:
    build: ./video_service
    ports:
      - "5002:5002"
